dist: trusty
sudo: required

services:
  - docker

before_install:
  - docker build -t probcomp/notebook .
  - docker build -t probcomp/notebook:edge -f Dockerfile-edge .
script:
  - docker run probcomp/notebook sh -c 'cd tutorials && python -m pytest ${1+"$@"}' -- ${1+"$@"}
